spring:
  datasource:
    url: cloudlibrary/rds/library/mysql
    username: cloudlibrary/rds/library/mysql
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  jackson:
    serialization:
      indent-output: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    com:
      cloudlibrary: debug
    web: trace
    org:
      springframework:
        web: trace

